do not display text overlay on hubs for shows and movies (+ exception)
Exception: Continue Watching. Include the text over, as it always shows
the cards as artwork. The continue watching hub will also use the
episodes grandparent title instead of the season string.